### ISSUE TITLE
Release Mode Android | couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by lance-blo** [azihsoyn/flutter_mlkit#36]
Hi all,

I'm having an issue when using the library and building a release apk for Android.

`flutter -v doctor`

[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.285], locale fr-FR)
    • Flutter version 0.7.3 at C:\Users\lance\Dev\SDK\flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\lance\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] Connected devices (1 available)
    • ONEPLUS A3003 • 94e1fa9b • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Reproduce issue**

1) Create an empty flutter project

2) Update pubspec.yaml to

` mlkit: ^0.6.2
  image_picker:`

3) run $ flutter build apk

4) I am getting the following

`  AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/eu.my-domain.mlkit-test-VnjMxahfeCGMItX8kAUbAg==/base.apk"],nativeLibraryDirectories=[/data/app/eu.my-domain.mlkit-test-VnjMxahfeCGMItX8kAUbAg==/lib/arm64, /data/app/eu.my-domain.mlkit-test-VnjMxahfeCGMItX8kAUbAg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"`

This seems to be linked to 
https://github.com/flutter/flutter/issues/18939
https://github.com/flutter/flutter/issues/18494

Any ideas why this is hapenning?

**Comment by lance-blo** [comment]
1.a. Replace main.dart with

https://pub.dartlang.org/packages/mlkit#-example-tab-

**Comment by sayurikunugi** [comment]
Hi,

when you build apk, try the command.
flutter build apk --release --target-platform android-arm64

if you still have the same 'couldn't find "libflutter.so"' error, 
your device could be 32bit.

in that case, change your android build.gradle file something like below.
build.gradle
defaultConfig {
    ndk{
        abiFilters "armeabi-v7a"
    }
…
}

and try the command below.
flutter build apk --release --target-platform android-arm

**Comment by lance-blo** [comment]
Thanks. Right, as described here [flutter/issues/18939](https://github.com/flutter/flutter/issues/18939), this makes the app run. 

But my problem is that I will not be able to publish the app to the PlayStore as I will be targeting only one architecture.

I have tested several other plugins that are not creating the described problem.

Any ideas as to why this is happening?

**Comment by azihsoyn** [comment]
Hi, Thanks reporting and commenting! 

I'll check it later ASAP! 😄

**Comment by sayurikunugi** [comment]
that's true.
my app works fine both for 64-bit and 32-bit, when using 32bit build.
how about yours?

**Comment by Albert221** [comment]
Is there any update on this?

**Comment by azihsoyn** [comment]
Hi, @Albert221 

https://github.com/azihsoyn/flutter_mlkit/issues/36#issuecomment-421543617 does not resolve your issue?

**Comment by RockCoder7** [comment]
> Hi,
> 
> when you build apk, try the command.
> flutter build apk --release --target-platform android-arm64
> 
> if you still have the same 'couldn't find "libflutter.so"' error,
> your device could be 32bit.
> 
> in that case, change your android build.gradle file something like below.
> build.gradle
> defaultConfig {
> ndk{
> abiFilters "armeabi-v7a"
> }
> …
> }
> 
> and try the command below.
> flutter build apk --release --target-platform android-arm

This works for me! Thank you sooooooooo much!

**Comment by afamobius** [comment]
> Ok after several testing I have the below (my device is 64-bit).
> 
> Targeting 64-bit architecture does work.
> `flutter build apk --release --target-platform android-arm64`
> 
> However targeting 32-bit reproduces the issue.
> `flutter build apk --release --target-platform android-arm`
> 
> To get the 32-bit version running I need to use:
> `defaultConfig { ndk{ abiFilters "armeabi-v7a" } }`

hey , so first thank you , second does that mean I have to produce two different apks? or the first command is enough for the two versions ?

**Comment by kelvinji2009** [comment]
@afamobius What's your minSdkVersion?

**Comment by shoxter** [comment]
@afamobius So is it backwards compatible without `defaultConfig { ndk{ abiFilters "armeabi-v7a" } }` or you needed that for it to be backwards compatible?

**Comment by dhaval0122** [comment]
any solution? i have upgrade flutter to 1.7.4 still app crash while open.

**Comment by nimesh1997** [comment]
After Upgraded **flutter to 1.7.4**  new error comes how to resolve this in flutter version?
```
> **/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
>  - 'StringBuffer' is from 'dart:core'.                                  
>  - 'Iterable' is from 'dart:core'.                                      
>  - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart'**
```

_

**Comment by amreniouinnovent** [comment]
this works for me
defaultConfig {
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'
        }
    }

**Comment by marvinsxtr** [comment]
After none of the solutions above worked for me, i looked into the [documentation](https://flutter.dev/docs/deployment/android#build-an-apk) and found that it worked fine when i ran
`flutter build apk --split-per-abi`
and picked the release-apk corresponding to my system architecture.

**Comment by kw2019ltd** [comment]
still getting same issue with new flutter version even the pp bundle contin both 32 and 64

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/kw.ltd.instagram_app-qzaBIcobpGp9vljkJD7Y1Q==/base.apk"],nativeLibraryDirectories=[/data/app/kw.ltd.instagram_app-qzaBIcobpGp9vljkJD7Y1Q==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
       at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
       at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
       at android.app.ActivityThread.access$1300(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by aldwnesx** [comment]
> still getting same issue with new flutter version even the pp bundle contin both 32 and 64
> 
> Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/kw.ltd.instagram_app-qzaBIcobpGp9vljkJD7Y1Q==/base.apk"],nativeLibraryDirectories=[/data/app/kw.ltd.instagram_app-qzaBIcobpGp9vljkJD7Y1Q==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
> at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
> at java.lang.System.loadLibrary(System.java:1667)
> at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
> at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
> at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
> at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
> at android.app.ActivityThread.access$1300(ActivityThread.java:219)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
> at android.os.Handler.dispatchMessage(Handler.java:107)
> at android.os.Looper.loop(Looper.java:214)
> at android.app.ActivityThread.main(ActivityThread.java:7356)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Same..

**Comment by aldwnesx** [comment]
> this works for me
> defaultConfig {
> ndk {
> abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'
> }
> }

do you run build appbundle or apk or splitapk
?

**Comment by kw2019ltd** [comment]
We need fix from the flutter team

**Comment by AlekseyMak** [comment]
Hello. Trying to build flutter app for **x86 32 bit**, but libflutter.so is not generated. 
How can i fix this?

armv7, arm46 and x86_64 are generated without issues

**Comment by devDeejay** [comment]
Any fixes guys :( ?

**Comment by z85510** [comment]
I have the same problem.
I've tried to add
 ```
ndk{
abiFilters "armeabi-v7a"
}
```
but after adding this line in build.gradle then my app doesn't work on x86 emulators.

**Comment by emadd** [comment]
Getting this in production.  Not cool.

Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.seachangedigital.quiverus-1/base.apk"],nativeLibraryDirectories=[/data/app/com.seachangedigital.quiverus-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
java.lang.Runtime.loadLibrary0 (Runtime.java:984)
java.lang.System.loadLibrary (System.java:1582)
io.flutter.embedding.engine.loader.FlutterLoader.startInitialization
io.flutter.embedding.engine.loader.FlutterLoader.startInitialization
io.flutter.view.FlutterMain.startInitialization
io.flutter.app.FlutterApplication.onCreate
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1024)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5405)
android.app.ActivityThread.-wrap2 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1546)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6121)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)

Firebase Crashlytics says the devices are Android 7.1.2 (TaintArt for x86) and 8.1.0 (Nexus 5X)

**Comment by premtemp1** [comment]
Getting the same error as @emadd ..
any solution
this my filter setting --
abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'

**Comment by rlecheta** [comment]
I'm integrating flutter in some existing app and I have the same error
/base.apk!/lib/x86_64, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
And this doesn't solve the problem:
ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
I can build a release apk, but I can't run it on emulador using Android Studio.

**Comment by uzumaki258** [comment]
I have the same issue with Android 5.1 and 5.1.1:
nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libflutter.so"
I have used it.
buildTypes {
       release {
           // other configs
            ndk {
                abiFilters 'armeabi-v7a','arm64-v8a','x86_64'
            }
           signingConfig signingConfigs.release
       }
targetSdkVersion 29

**Comment by DaBlitzStein** [comment]
Same here, tested all configurations proposed. 2 years and still open.

**Comment by blamath20** [comment]
Still not working...missing libflutter.so from x86 Flutter 2.8.1
