### ISSUE TITLE
android custom FirebaseMLException.

### ISSUE THREAD

**Issue by liyoung1992** [azihsoyn/flutter_mlkit#66]
W/FirebaseModelManager( 2101): The remote model name is already registered: coco
E/ModelResourceManager( 2101): Error preloading model resource
E/ModelResourceManager( 2101): com.google.firebase.ml.common.FirebaseMLException: Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:33)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zza(Unknown Source:109)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zzln(Unknown Source:105)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoa.zzf(Unknown Source:56)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoc.zzlu(Unknown Source:7)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoc.call(Unknown Source:24)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source:30)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zznq.run(Unknown Source:2)
E/ModelResourceManager( 2101): 	at android.os.Handler.handleCallback(Handler.java:789)
E/ModelResourceManager( 2101): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source:6)
E/ModelResourceManager( 2101): 	at android.os.Looper.loop(Looper.java:164)
E/ModelResourceManager( 2101): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ModelResourceManager( 2101): Caused by: com.google.firebase.ml.common.FirebaseMLException: Failed to get model URL
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:62)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:2)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzph.zzb(Unknown Source:3)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmh(Unknown Source:79)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmb(Unknown Source:19)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpk.load(Unknown Source:26)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:41)
E/ModelResourceManager( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:14)
E/ModelResourceManager( 2101): 	... 12 more
E/ModelResourceManager( 2101): Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
E/ModelResourceManager( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:71)
E/ModelResourceManager( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:84)
E/ModelResourceManager( 2101): 	at com.google.firebase.iid.zzt.then(Unknown Source:4)
E/ModelResourceManager( 2101): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
E/ModelResourceManager( 2101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ModelResourceManager( 2101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ModelResourceManager( 2101): 	at java.lang.Thread.run(Thread.java:764)
W/System.err( 2101): com.google.firebase.ml.common.FirebaseMLException: Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:33)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zza(Unknown Source:109)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zzln(Unknown Source:105)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoa.zzf(Unknown Source:56)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznt.call(Unknown Source:3)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source:30)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznq.run(Unknown Source:2)
W/System.err( 2101): 	at android.os.Handler.handleCallback(Handler.java:789)
W/System.err( 2101): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source:6)
W/System.err( 2101): 	at android.os.Looper.loop(Looper.java:164)
W/System.err( 2101): 	at android.os.HandlerThread.run(HandlerThread.java:65)
W/System.err( 2101): Caused by: com.google.firebase.ml.common.FirebaseMLException: Failed to get model URL
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:62)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:2)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzph.zzb(Unknown Source:3)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmh(Unknown Source:79)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmb(Unknown Source:19)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpk.load(Unknown Source:26)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:41)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:14)
W/System.err( 2101): 	... 11 more
W/System.err( 2101): Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
W/System.err( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:71)
W/System.err( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:84)
W/System.err( 2101): 	at com.google.firebase.iid.zzt.then(Unknown Source:4)
W/System.err( 2101): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/System.err( 2101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err( 2101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err( 2101): 	at java.lang.Thread.run(Thread.java:764)
E/FirebaseModelInterpreter( 2101): Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
W/System.err( 2101): com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.ml.common.FirebaseMLException: Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
W/System.err( 2101): 	at com.google.android.gms.tasks.zzu.getResult(Unknown Source:15)
W/System.err( 2101): 	at com.azihsoyn.flutter.mlkit.MlkitPlugin$10.then(MlkitPlugin.java:358)
W/System.err( 2101): 	at com.azihsoyn.flutter.mlkit.MlkitPlugin$10.then(MlkitPlugin.java:350)
W/System.err( 2101): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/System.err( 2101): 	at android.os.Handler.handleCallback(Handler.java:789)
W/System.err( 2101): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err( 2101): 	at android.os.Looper.loop(Looper.java:164)
W/System.err( 2101): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
W/System.err( 2101): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2101): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
W/System.err( 2101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
W/System.err( 2101): Caused by: com.google.firebase.ml.common.FirebaseMLException: Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:33)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zza(Unknown Source:109)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpr.zzln(Unknown Source:105)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoa.zzf(Unknown Source:56)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznt.call(Unknown Source:3)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznn.zza(Unknown Source:30)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zznq.run(Unknown Source:2)
W/System.err( 2101): 	at android.os.Handler.handleCallback(Handler.java:789)
W/System.err( 2101): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source:6)
W/System.err( 2101): 	at android.os.Looper.loop(Looper.java:164)
W/System.err( 2101): 	at android.os.HandlerThread.run(HandlerThread.java:65)
W/System.err( 2101): Caused by: com.google.firebase.ml.common.FirebaseMLException: Failed to get model URL
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:62)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoy.zza(Unknown Source:2)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzph.zzb(Unknown Source:3)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmh(Unknown Source:79)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzoz.zzmb(Unknown Source:19)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzpk.load(Unknown Source:26)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:41)
W/System.err( 2101): 	at com.google.android.gms.internal.firebase_ml.zzon.zza(Unknown Source:14)
W/System.err( 2101): 	... 11 more
W/System.err( 2101): Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
W/System.err( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:71)
W/System.err( 2101): 	at com.google.firebase.iid.zzs.zza(Unknown Source:84)
W/System.err( 2101): 	at com.google.firebase.iid.zzt.then(Unknown Source:4)
W/System.err( 2101): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/System.err( 2101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err( 2101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err( 2101): 	at java.lang.Thread.run(Thread.java:764)
E/FirebaseModelInterpreter( 2101): com.google.firebase.ml.common.FirebaseMLException: Remote model load failed with the model options: Local model name: unspecified. Remote model name: coco. 
I/zygote64( 2101): Compiler allocated 4MB to compile int com.google.android.gms.internal.firebase_ml.zzwi.zzaa(java.lang.Object)
I/flutter ( 2101): original Image Size : Size(3504.0, 2336.0)
I/flutter ( 2101): offset : Offset(0.0, 210.0)
I/flutter ( 2101): configuration : ImageConfiguration(bundle: PlatformAssetBundle#dfb5d(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, size: Size(360.0, 240.0), platform: android)
I/flutter ( 2101): rect container : Rect.fromLTRB(0.0, 210.0, 360.0, 450.0)
E/FirebaseInstanceId( 2101): Token retrieval failed: SERVICE_NOT_AVAILABLE
E/FirebaseInstanceId( 2101): Token retrieval failed: SERVICE_NOT_AVAILABLE

**Comment by azihsoyn** [comment]
Hi, @liyoung1992!

Thank you for reporting!

**Comment by RafaelRViana** [comment]
Same problem here. Did you find a solution?

**Comment by yashdesai30** [comment]
Chutyo
